version: "3.9"
services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legalia
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build: ./apps/api
    env_file: .env
    depends_on: [postgres, redis]
    ports: ["8080:8080"]
    command: ["./api"]

  worker:
    build: ./apps/worker
    env_file: .env
    depends_on: [postgres, redis]
    command: ["./worker"]

  web:
    build: ./apps/web
    depends_on: [api]
    ports: ["5173:5173"]
    command: ["npm","run","dev","--","--host"]

volumes:
  pgdata:
