version: "3.9"

services:
  db:
    image: ankane/pgvector:latest
    container_name: alra_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legal_assistant
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d legal_assistant"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    container_name: alra_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Runs migrations once on startup, then exits
  migrate:
    image: migrate/migrate:4
    container_name: alra_migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../apps/api/migrations:/migrations:ro
    # IMPORTANT: keep this DSN in sync with .env DATABASE_URL (host must be 'db' inside the network)
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/legal_assistant?sslmode=disable",
      "up"
    ]
    restart: "no"

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: alra_api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"

  worker:
    build:
      context: ../apps/worker
    container_name: alra_worker
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
